name: Test Redistribute

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test-redistribute:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.4.15"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
      - name: Install build dependencies
        run: uv pip install build
      - name: Build source distribution
        run: python -m build --sdist
      - name: Decompress source distribution
        run: |
          cd dist
          tar xvf annotated-doc*.tar.gz
      - name: Install test dependencies
        run: |
          cd dist/annotated-doc*/
          uv sync
      - name: Run source distribution tests
        run: |
          cd dist/annotated-doc*/
          bash scripts/test.sh
      - name: Build wheel distribution
        run: |
          cd dist
          uv pip wheel --no-deps annotated-doc*.tar.gz
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  # https://github.com/marketplace/actions/alls-green#why
  test-redistribute-alls-green:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - test-redistribute
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
